version: '3.8'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tesseract-app
    depends_on:
      - database
    ports:
      - 127.0.0.1:3999:3999
    volumes:
      - ./output:/app/output
  database:
    image: mysql:8
    container_name: tesseract-db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.db:/var/lib/mysql
    env_file: .env
    cap_add:
      - SYS_NICE
    ports:
      - 127.0.0.1:3306:3306
  pma:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: tesseract-pma
    environment:
      - PMA_HOST=database
    ports:
      - 127.0.0.1:8009:80
    depends_on:
      - database
    links:
      - database